version: '2'
services:
  webapp:
    build:
      context: ./chinook
      args:
        username: $django_superuser_name
        password: $django_superuser_password
        email: $django_superuser_email
        port: $django_port
    container_name: webapp
    env_file:
      - .env
    ports:
     - "${django_port}:${django_port}"
    volumes:
     - .:/chinook
    depends_on:
     - postgres
  postgres:
    container_name: postgres
    image: postgres
